<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sws_xsd="http://webservices.sabre.com/sabreXML/2011/10" xmlns:sws="https://webservices.sabre.com/websvc" xmlns:eb="http://www.ebxml.org/namespaces/messageHeader" xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/12/secext" targetNamespace="https://webservices.sabre.com/websvc">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://webservices.sabre.com/sabreXML/2011/10" schemaLocation="OTA_AirBookLLS2.2.0RQRS.xsd"/>
			<xsd:import namespace="http://www.ebxml.org/namespaces/messageHeader" schemaLocation="msg-header-2_0.xsd"/>
			<xsd:import namespace="http://schemas.xmlsoap.org/ws/2002/12/secext" schemaLocation="wsse.xsd"/>
			<xsd:import namespace="http://services.sabre.com/STL/v01" schemaLocation="STL_For_SabreProtocol_v.1.2.0.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="OTA_AirBookInput">
		<wsdl:part name="header" element="eb:MessageHeader"/>
		<wsdl:part name="header2" element="wsse:Security"/>
		<wsdl:part name="body" element="sws_xsd:OTA_AirBookRQ"/>
	</wsdl:message>
	<wsdl:message name="OTA_AirBookOutput">
		<wsdl:part name="header" element="eb:MessageHeader"/>
		<wsdl:part name="header2" element="wsse:Security"/>
		<wsdl:part name="body" element="sws_xsd:OTA_AirBookRS"/>
	</wsdl:message>
	<wsdl:portType name="OTA_AirBookPortType">
		<wsdl:operation name="OTA_AirBookRQ">
			<wsdl:input message="sws:OTA_AirBookInput"/>
			<wsdl:output message="sws:OTA_AirBookOutput"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="OTA_AirBookSoapBinding" type="sws:OTA_AirBookPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="OTA_AirBookRQ">
			<soap:operation soapAction="OTA_AirBookLLSRQ"/>
			<wsdl:input>
				<soap:header message="sws:OTA_AirBookInput" part="header" use="literal"/>
				<soap:header message="sws:OTA_AirBookInput" part="header2" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header message="sws:OTA_AirBookOutput" part="header" use="literal"/>
				<soap:header message="sws:OTA_AirBookOutput" part="header2" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="OTA_AirBookService">
		<wsdl:port name="OTA_AirBookPortType" binding="sws:OTA_AirBookSoapBinding">
			<soap:address location="$SWS_URL$"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>